---
report:
    html: "/tmp/report/"
    csv: "/tmp/report.csv"
    json: "/tmp/report.json"
    violations: "/tmp/violations.xml"

plugins:
    junit:
        file: "/tmp/junit.xml" # if defined, analyze junit report
